# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='r',
            new_name='A',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='u',
            new_name='T',
        ),
        migrations.RemoveField(
            model_name='input',
            name='s',
        ),
        migrations.RemoveField(
            model_name='input',
            name='t',
        ),
        migrations.AddField(
            model_name='input',
            name='b',
            field=models.FloatField(default=0.1, verbose_name=' damping coefficient (kg/s)'),
        ),
        migrations.AddField(
            model_name='input',
            name='w',
            field=models.FloatField(default=6.283185307179586, verbose_name=' frequency (1/s)'),
        ),
    ]
