# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 21:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='s',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='t',
            field=models.FloatField(default=datetime.datetime(2016, 2, 13, 21, 10, 48, 235863, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='input',
            name='u',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
