# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160213_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='r',
        ),
        migrations.RemoveField(
            model_name='input',
            name='s',
        ),
        migrations.RemoveField(
            model_name='input',
            name='t',
        ),
        migrations.RemoveField(
            model_name='input',
            name='u',
        ),
        migrations.AddField(
            model_name='input',
            name='A',
            field=models.FloatField(default=1.0, verbose_name=' amplitude (m)'),
        ),
        migrations.AddField(
            model_name='input',
            name='T',
            field=models.FloatField(default=18, verbose_name=' time interval (s)'),
        ),
        migrations.AddField(
            model_name='input',
            name='b',
            field=models.FloatField(default=0.0, verbose_name=' damping coefficient (kg/s)'),
        ),
        migrations.AddField(
            model_name='input',
            name='w',
            field=models.FloatField(default=6.283185307179586, verbose_name=' frequency (1/s)'),
        ),
    ]
