# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160215_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='A',
            new_name='r',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='b',
            new_name='s',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='T',
            new_name='u',
        ),
        migrations.RemoveField(
            model_name='input',
            name='w',
        ),
        migrations.AddField(
            model_name='input',
            name='t',
            field=models.FloatField(default=6.283032, verbose_name=' frequency (1/s)'),
        ),
    ]
