# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='v',
            field=models.CharField(default=1, max_length=200, verbose_name=' txt filename '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='s',
            field=models.FloatField(default=2.0, verbose_name=' damping coefficient (kg/s)'),
        ),
    ]
