# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0002_auto_20160219_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='v',
        ),
        migrations.AlterField(
            model_name='input',
            name='t',
            field=models.CharField(max_length=200, verbose_name=' txt filename '),
        ),
    ]
