# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_auto_20160219_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='f',
            field=models.CharField(default=1, max_length=200, verbose_name=' txt filename '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='t',
            field=models.FloatField(default=6.283032, verbose_name=' frequency (1/s)'),
        ),
    ]
