# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0004_auto_20160219_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='f',
            field=models.CharField(default='outputfile_from_views_index_math_2p', max_length=200, verbose_name=' txt filename '),
        ),
    ]
